### PR TITLE
Write README.md 

### LINKED ISSUE #3: Documentation
Start writing documentation for the project. This must not be a final version of the README.md, but it should get things started. 

More information should be added on the go.

### PR DESCRIPTION
**Pull request by medkamilmel**
Fixes #3.
Don't hesitate to add something in the Contributions part if you want to!

### CODE REVIEW

**Comment by ArnPellesGit** [comment]
Why are there 17 commits linked to this one? ^^

**Comment by medkamilmel** [comment]
> Why are there 17 commits linked to this one? ^^

no idea, I must've done something wrong when pulling before committing

**Comment by ArnPellesGit** [comment]
Here are my thoughts on the readme:
* Love the header with Browse code, report a bug, request a feature.
* You refer to the decide() method kind of out of context in my opinion. Perhaps we can add something like "The main function we've considered here is located in src/main/.../Decide.java() "
* Do we need to mention what brew is since we're referring to how to install packages with brew?

Overall it looks solid to me. Very informative but concise. Great

**Review by capitanu — APPROVED** [review]
LGTM

**Review by ArnPellesGit — APPROVED** [review]
LGTM too now that it's fixed :)

**Review by HakuPiku — APPROVED** [review]

**Review by capitanu — APPROVED** [review]

**Pull request merged**
